# Generated by Django 4.0.3 on 2022-04-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_message_options_user_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
    ]
